### ISSUE TITLE
Special characters don't work with download counter

### ISSUE THREAD

**Issue by MaStr** [LibraryBox-Dev/LibraryBox-core#12]
USB stick formatted with FAT32 with files to be shared placed in \LibraryBox\Shared\video on a Windows host.

Most files appear and are clickable. The only two files containing umlauts in the filenames ("Gehäuse.jpg") show with their names empty, i.e. there is a little icon at the beginning of the line and a directory entry line. Clicking on that line leads to the LibraryBox homepage, not to the file. The files with Umlaute are on the stick, "next" to the others, but complete inacessible from the LibraryBox.

**Comment by MaStr** [comment]
Only very exotic chars break. the DL link. .. is that a limitation we can live with?

**Comment by griffey** [comment]
LOL. Only _very_ exotic ones? :-) Any major character sets? 

Otherwise, yes...let's do what we can now, and keep thinking about future betterments. :-)
