### ISSUE TITLE
Link to startpage topleft has wrong link

### ISSUE THREAD

**Issue by MaStr** [LibraryBox-Dev/LibraryBox-core#21]
it referes to /Content with a capitalized C instead of a non-capitalized.

No user impact, but if you run in non standard environments, it always creates a wrong redirect.

**Comment by MaStr** [comment]
https://github.com/LibraryBox-Dev/LibraryBox-core/commit/e349ac7494bba3714b8941eb11430080fcbf4c0b
You fixed it, but somehow it wasn't included for me (or maybe it wasn't overwritten on my end because I didn't delete the Content folder).

Did you verify it? Just for my records ;)

**Comment by griffey** [comment]
In the release2.1 branch, I did fix it, just checked the github. It appears
fixed to me. :-)

Jason
