### ISSUE TITLE
Directory listings are broken w/ spaces

### ISSUE THREAD

**Issue by griffey** [LibraryBox-Dev/LibraryBox-core#23]
If a directory in /Shared has spaces in the name, the system errors and redirects to the index page. Same directory without spaces works appropriately. Spaces in filenames appear to not be a problem.

**Comment by MaStr** [comment]
Problem is maybe this line line https://github.com/LibraryBox-Dev/LibraryBox-core/blob/release-2.1/customization/www_librarybox/dir-generator.php#L397

The file on the box is   /opt/piratebox/www/dir-generator.php

````PHP
print "<tr><td class='n'><a id='folder' href='" . urlencode($folder['name']). "'>" .get_utf8_encoded($folder['name']). "</a>/</td>";
````

Can you try on your machine (if you are currently testing) to change it to

````PHP
print "<tr><td class='n'><a id='folder' href='" . $folder['name'] . "'>" .get_utf8_encoded($folder['name']). "</a>/</td>";
````

**Comment by griffey** [comment]
That does it. You want to fix the branch, or shall I?

Jason
