### ISSUE TITLE
miniDLNA toggle in box_init_setup.sh throws error when disabling

### ISSUE THREAD

**Issue by griffey** [LibraryBox-Dev/LibraryBox-core#24]
The box_init_setup.sh works to turn ON, but not to turn OFF, the miniDLNA server.

*****
root@T1WQQRWR:~# box_init_setup.sh
-------------------------------------
 
   1 - Setting password and enable SSH
   2 - Set date & time (enable timesave)
   3 - Start FTP configuration 
   4 - minidlna  disable

 Everything else causes an exit
 
 Choose an option: 4
Syntax: /etc/init.d/minidlna [command]

Available commands:
	start	Start the service
	stop	Stop the service
	restart	Restart the service
	reload	Reload configuration files (or restart if that fails)
	enable	Enable service autostart
	disable	Disable service autostart

minidlna disabled and stopped
-------------------------------------
 
   1 - Setting password and enable SSH
   2 - Set date & time (enable timesave)
   3 - Start FTP configuration 
   4 - minidlna  disable

 Everything else causes an exit
*****

It appears to stop the service, but the menu doesn't reflect that, and it isn't clear if it's stopped or not...

**Comment by MaStr** [comment]
confirmed,
https://github.com/LibraryBox-Dev/LibraryBox-Installer/blob/master/files/bin/box_init_setup.sh#L112 
"disabled", should be "disable"  only
