### ISSUE TITLE
Character encoding issue

### ISSUE THREAD

**Issue by griffey** [LibraryBox-Dev/LibraryBox-core#30]
* Files and directories with UTF-8 encoded umlauts display properly in the listing. 
* Files and directories with ASCII encoded umlauts display an error character. 
* Files with either Ascii or UTF will download if clicked, and are captured by stats php script (the count increments) but the filename in the stats display is "null". Screenshot attached.
* Directories with either utf or ascii can be clicked and work, and files inside of either directory without special characters download and are collected by stats script properly.

**Comment by MaStr** [comment]
The bugreport is based on the following manual patch requested by myself:
``` sed -i  's| urlencode| rawurlencode|' /opt/piratebox/www/dir-generator.php ``` 

Ok, thanks for testing and documenting. Let's summarize that in a bit different way:

1. urlrawencode helps to bring the corrent URL to the dl-stats connection
2. urlrawencode, makes the download work because of the internal conversion of the URL parameters
3. Directories work 

So we have to sort out two other tings:

a. Correct ASCII encoded umlauts in files & directories
b. Correct display in the statistics 

Let's start with the correct display inside the directory listing.

**Comment by MaStr** [comment]
And BTW: of course, undefinded charset input  to something beautiful is like magic, I guess.
And never forget: "shit in, shit out" ;)

**Comment by MaStr** [comment]
Can't verify that:
* Files and directories with ASCII encoded umlauts display an error character

http://www.gymel.com/charsets/ISO8859-15.html

0xF6  => ö  in ISO8859-15


````
echo -en 'Test\xF6.txt' | xargs  touch 
php-cli /opt/piratebox/bin/hex_dump_directory.php 

Encoding detected:    
     0 : 54 65 73 74 f6 2e 74 78 74 [Test..txt]

Converted to UTF-8: TestÃ¶.txt 
     0 : 54 65 73 74 c3 b6 2e 74 78 74 [Test...txt]
````

HTML Code shows a proper ö
````
<a id='doc' href='/dl_statistics_counter.php?DL_URL=/Shared%2FTest%F6.txt'>Testö.txt</a><
````

**Comment by MaStr** [comment]
Funny, the Ü does not work:
````
[matze@shrimpy iso]$ echo $LANG
de_DE@euro
[matze@shrimpy iso]$ echo -en 'Ü' | hexdump -C
00000000  dc                                                |Ü|
00000001
````
On the LibraryBox:
````
Überwachung_ascii.txt
Encoding detected:  UTF-8  
     0 : dc 62 65 72 77 61 63 68 75 6e 67 5f 61 73 63 69 [.berwachung_asci]
    10 : 69 2e 74 78 74 [i.txt]
````

that php function is the root cause: mb_detect_encoding
It delivers "yeah, UTF8" instead of "ISO..." !

**Comment by griffey** [comment]
As it turns out, that was the character I used. :-/

J

**Comment by MaStr** [comment]
(see my post update online)
I tested is with your character again, on purpose..

**Comment by MaStr** [comment]
UTF-8 helper tool: http://www.cogsci.ed.ac.uk/~richard/utf-8.cgi

**Comment by MaStr** [comment]
Next try to improve it would be to apply the following

````
sed -i 's|($string, "auto" )|($string, "UTF-8, ISO-8859-1" )|' /opt/piratebox/www/dir-generator.php
````

That fixed it for me **in that case**.

**Comment by MaStr** [comment]
This seems to fix it, BUT I recognized issues with a conflict between the i10n function and the dynamic ajax fetch of the statistics. The text won't be replaced. The i10n seems to always add something into the front :(

**Comment by griffey** [comment]
Crap. So no translations?

J

**Comment by MaStr** [comment]
No, the text "Nothing's been downloaded yet. Why not start this party?" is always displayed

**Comment by griffey** [comment]
Ah! If that's the case we should just kill that text.

J
