### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by griffey** [LibraryBox-Dev/LibraryBox-core#31]
From user @jochmann:
****
An img tag containing SVG does not display in web pages served from librarybox.

Some troubleshooting and googling got me to an answer on stackexchange. Unfortunately I'm not able to manually edit the htaccess on the librarybox - or can I and have looked in the wrong place?

> This can also be caused by sending the svg as plain/text and not as an image/svg+xml. In Apache you can fix this by adding to your .htaccess file -
>
> AddType image/svg+xml svg svgz
> AddEncoding gzip svgs
***

Obviously we don't use Apache, but Lighttpd needs a similar encoding added:

Add the following lighttpd.conf's default configuration of mimetype.assign:

".svg" => "image/svg+xml",

**Comment by griffey** [comment]
Fixed via 17250a7

**Comment by MaStr** [comment]
Reopening for fixing in upstream
