### ISSUE TITLE
Chatbox not working in 2.1?

### ISSUE THREAD

**Issue by ndelapena** [LibraryBox-Dev/LibraryBox-core#33]
How do I enable chat in v.2.1? It doesn't seem to work - There is no chat box under 'Chat'...?

**Comment by MaStr** [comment]
?? Chatbox is enabled per default on LibraryBox since ever. 
Maybe it is an refreshing problem with your client?

Sounds weired, can you attach a picture please?

many thanks
best regards
Matthias

**Comment by ndelapena** [comment]
Please disregard... my firefox-based html editor removed the shoutbox when I edited index.html because it returned ajaxerror... fixed it using text-based editor... tnx!b
