### ISSUE TITLE
UTF-8 support on file names/directory names

### ISSUE THREAD

**Issue by kirkdwilson** [LibraryBox-Dev/LibraryBox-core#34]
The current build does not fully support UTF-8 character formats due to a difference in the character set support.  We have fixed this issue by changing the mount option in ./etc/ext.config for the USB drive:

ext_usbmount_options="utf8,umask=0,noatime,rw

This will then allow for the full UTF-8 character sets to be used in both file name and folder names

**Comment by MaStr** [comment]
Thanks for the feedback, it is already included into the development builds: https://github.com/PirateBox-Dev/openwrt-piratebox-feed/commit/3fae8f01795a50f58baa4c4debac1e15c85613f8 

I'm not quite sure that solves everything, but maybe helps. We will see
